version: '3'
services:
  app:
    build: ./app
    volumes:
      - ./app/source:/app           
    ports:
      - "8000:8000"   
    networks:
      - mynetwork

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - mynetwork

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources    
    ports:
      - "3000:3000"
    networks:
      - mynetwork

networks:
  mynetwork: